# Generated by Django 5.1.6 on 2026-04-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='vita.profilvendeur'),
        ),
    ]
