# Generated by Django 5.1.6 on 2026-04-02 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0002_alter_produit_id_vendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL),
        ),
    ]
