# Generated by Django 5.1.6 on 2026-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0003_alter_produit_id_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='tag',
            field=models.CharField(blank=True, choices=[('BESTSELLER', 'Bestseller'), ('NEW_ARRIVAL', 'New Arrival'), ('TOP_RATED', 'Top Rated')], max_length=20, null=True),
        ),
    ]
