# Generated by Django 5.1.6 on 2026-04-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0004_produit_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='tag',
            field=models.CharField(blank=True, choices=[('MEILLEURES_VENTES', 'Meilleures ventes'), ('NOUVEAUTES', 'Nouveautés'), ('MIEUX_NOTES', 'Les mieux notés')], max_length=20, null=True),
        ),
    ]
