# Generated by Django 5.1.6 on 2026-04-18 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0005_alter_produit_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='id_vendeur',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='id_vendeur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_vendeur', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], max_length=30),
        ),
    ]
