# Generated by Django 5.1.6 on 2026-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0006_remove_commande_id_vendeur_lignecommande_id_vendeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=30),
        ),
    ]
