# Generated by Django 5.1.6 on 2026-04-20 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0008_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, numbers and spaces', regex='^[\\w\\s]+$')]),
        ),
    ]
