# Generated by Django 5.1.6 on 2026-04-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('confirmee', 'Confirmee'), ('expediee', 'Expediee'), ('livree', 'Livree'), ('annulee', 'Annulee')], default='en_attente', max_length=20),
        ),
    ]
