# Generated by Django 5.1.6 on 2026-04-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_deleted_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='is_deleted_by_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
