# Generated by Django 5.1.6 on 2026-04-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0012_commande_is_deleted_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='is_deleted_by_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
