# Generated by Django 5.1.6 on 2026-04-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0013_lignecommande_is_deleted_by_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='numero_suivi',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='numero_suivi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('collectee', 'Collectée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
