# Generated by Django 5.1.6 on 2026-05-10 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0014_remove_commande_numero_suivi_remove_commande_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilvendeur',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
