# Generated by Django 5.1.6 on 2026-05-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0015_profilvendeur_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='is_deleted_by_vendor',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='numero_suivi',
        ),
    ]
