# Generated by Django 5.1.6 on 2026-05-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0016_remove_commande_is_deleted_by_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='note_moyenne',
        ),
    ]
