# Generated by Django 5.1.6 on 2026-05-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0017_remove_produit_note_moyenne'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
