# Generated by Django 5.1.6 on 2026-05-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0020_produit_note_moyenne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='note_moyenne',
        ),
    ]
